<?php 
/* 	
If you see this text in your browser, PHP is not configured correctly on this hosting provider. 
Contact your hosting provider regarding PHP configuration for your site.

PHP file generated by Adobe Muse CC 2015.0.1.310
*/

require_once('form_process.php');

$form = array(
	'subject' => 'Отправка Main Form',
	'heading' => 'Отправка новой формы',
	'success_redirect' => 'tnx.html',
	'resources' => array(
		'checkbox_checked' => 'Отмечено',
		'checkbox_unchecked' => 'Флажок не установлен',
		'submitted_from' => 'Формы, отправленные с веб-сайта: %s',
		'submitted_by' => 'IP-адрес посетителя: %s',
		'too_many_submissions' => 'Недопустимо высокое количество отправок с этого IP-адреса за последнее время',
		'failed_to_send_email' => 'Не удалось отправить сообщение эл. почты',
		'invalid_reCAPTCHA_private_key' => 'Недействительный закрытый ключ reCAPTCHA.',
		'invalid_field_type' => 'Неизвестный тип поля \'%s\'.',
		'invalid_form_config' => 'Недопустимая конфигурация поля \"%s\".',
		'unknown_method' => 'Неизвестный метод запроса сервера'
	),
	'email' => array(
		'from' => '1z@bk.ru',
		'to' => '1z@bk.ru'
	),
	'fields' => array(
		'custom_U133' => array(
			'order' => 2,
			'type' => 'string',
			'label' => 'Ваше имя',
			'required' => true,
			'errors' => array(
				'required' => 'Поле \'Ваше имя\' не может быть пустым.'
			)
		),
		'custom_U124' => array(
			'order' => 1,
			'type' => 'string',
			'label' => 'Задайте вопрос и получите ответ через через 10 минут. Бесплатно!',
			'required' => false,
			'errors' => array(
			)
		),
		'custom_U139' => array(
			'order' => 4,
			'type' => 'string',
			'label' => 'Ваш телефон',
			'required' => true,
			'errors' => array(
				'required' => 'Поле \'Ваш телефон\' не может быть пустым.'
			)
		),
		'custom_U226' => array(
			'order' => 3,
			'type' => 'string',
			'label' => 'Ваш город',
			'required' => true,
			'errors' => array(
				'required' => 'Поле \'Ваш город\' не может быть пустым.'
			)
		)
	)
);

process_form($form);
?>
